# routes need to come up form properties file, cause it can change, we might have to reconfig everytime
server:
  port: 8181

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay= # to forward the oauth token
      routes:
        - id: route1   #<route id>
          uri: http://localhost:8990/  #<resource server url followed by a slash>
          predicates:
            - Path= /doora/r1/{segment} #<path under which you want to see it>
          filters:
            - RewritePath=/doora/r1/(?<segment>.*), /$\{segment}  #<re-write path logic>
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: <set a provider's name>
            client-id: <client id>
            client-secret: <client secret if applicable>
            scope: <scopes comma seperated values>
            authorization-grant-type: <grant type>
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # leave it as it is
        provider:
          <provider's name>:
            issuer-uri: <issuer url, ie. the server provides oauth2 support>