server:
  port: 8080

spring:
  application:
    name: gd-cloud-gateway
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider:
            client-id:
            client-secret:
            scope:
            authorization-grant-type:
            redirect-uri:
        provider:
          lkc:
            issuer-uri: